#!/usr/bin/env python2.7

import Gnuplot
import serial
import sys

ser = serial.Serial(sys.argv[1], 115200)

readings = []
g = Gnuplot.Gnuplot()
g.title("Arduino A0 V readings")
g('set style data lines')
g('set yrange [0:1024]')

while 1:
      reading=ser.readline().split();
      try:
            readingt = int(reading[0])
            readingv = int(reading[2])
            readings.append(readingv)
      except ValueError:
            pass
      finally:
            print reading

      if len(readings) > 300:
	    readings = readings[-10:]
	    g.plot(readings)
