#!/usr/bin/env python2.7

import Gnuplot
import serial
import sys

ser = None
if len(sys.argv) == 2:
      ser = serial.Serial(sys.argv[1], 115200)

readings = []
g = Gnuplot.Gnuplot()
g.title("Arduino A0 V readings")
g('set style data lines')
g('set yrange [0:1024]')

while 1:
      reading = None
      if ser is not None:
            reading = ser.readline().split()
      else:
            reading = sys.stdin.readline().split()
      try:
            if reading == []: break
            if len(reading) == 3:
                  readingt = int(reading[0])
                  readingv = int(reading[2])
                  readings.append(readingv)
      except ValueError:
            pass
      finally:
            print reading

      if len(readings) > 300:
	    readings = readings[-10:]
            g.plot(readings)
